### ISSUE TITLE
[BUG] Logical properties og Parcel

### ISSUE THREAD

**Issue by macbruker** [navikt/Designsystemet#1524]
## Hvilken av tjenestene våre gjelder det?

- [ ] `Komponenter`
- [x] `Stiler`
- [ ] `Ikoner`
- [ ] `Annet`

## Beskriv feilen/problemet

Det ser ut til at logical properties skaper problemer for de som bruker Parcel. Problemet ble oppdaget og meldt inn via Slack.
https://nav-it.slack.com/archives/C7NE7A8UF/p1653461757137309

Jeg har funnet to komponenter der vi bruker `text-align: start`

## Eksempel/Tilleggsinformasjon

Når vi bruker logical property som denne …
```CSS
 .navds-stepper__step-label { text-align: start }
```

… vil Parcel erstatte selectoren med denne koden. I tillegg kommer samme bit to ganger til med `-webkit-` vendor prefix. 
```CSS
.navds-stepper__step-label:not(:lang(ae)):not(:lang(ar)):not(:lang(arc)):not(:lang(bcc)):not(:lang(bqi)):not(:lang(ckb)):not(:lang(dv)):not(:lang(fa)):not(:lang(glk)):not(:lang(he)):not(:lang(ku)):not(:lang(mzn)):not(:lang(nqo)):not(:lang(pnb)):not(:lang(ps)):not(:lang(sd)):not(:lang(ug)):not(:lang(ur)):not(:lang(yi)) {
  text-align: left
}
.navds-stepper__step-label:is(:lang(ae), :lang(ar), :lang(arc), :lang(bcc), :lang(bqi), :lang(ckb), :lang(dv), :lang(fa), :lang(glk), :lang(he), :lang(ku), :lang(mzn), :lang(nqo), :lang(pnb), :lang(ps), :lang(sd), :lang(ug), :lang(ur), :lang(yi)) {
  text-align: right
}
```
Dette skaper sterke selectorer som overstyrer annen styling.
