### ISSUE TITLE
[Innspill til komponent]: <CopyButton />

### ISSUE THREAD

**Issue by markusra** [navikt/Designsystemet#1996]
### Tilbakemelding

Hei! Er det planlagt at knappen (variant `action`) skal oppføre seg likt som en tertiærknapp når den ikke er i beta lenger? Mao. mer likt som i skissene som ble delt på Slack tidligere?
![image](https://github.com/navikt/aksel/assets/5471549/fa037e53-fccb-48b4-bc58-d900fada22a0)
Det ser ut som at beta-versjonen ikke bruker de samme fargene i hvert fall. Vi har tenkt å bruke knappen ved siden av en annen tertiærknapp og da hadde det vært fint om de oppfører seg likt.

**Comment by KenAJoh** [comment]
Hei, setter denne til `wontfix` da vi ikke blir å endre på action sine farger i første omgang. Hvis dette fortsatt er ønsket, kan dette fikses med token `--ac-copybutton-action-hover-bg`
```css
// eks

.aksel-overrides{
   --ac-copybutton-action-hover-bg: var(--a-surface-action-subtle-hover);
}
```
