### ISSUE TITLE
Bug: Checkbox nested i Table

### ISSUE THREAD

**Issue by cskrov** [navikt/Designsystemet#2539]
### Tilbakemelding

Er det noen grunn til at `<Checkbox />` har denne stylen?

```css
.navds-table .navds-checkbox .navds-checkbox__label {
    padding: 0;
}
```

Den fjerner all luft i `<CheckboxGroup />` med flere checkboxer i tabeller.

For å jobbe seg rundt dette må man lage spesialiserte versjoner av checkbox-komponenter, avhengig av om de skal brukes i eller utenfor tabeller.
