### ISSUE TITLE
[NEW]: Sticky header i tabellar

### ISSUE THREAD

**Issue by ingfo** [navikt/Designsystemet#3728]
# Feature-request
Kunne setje header i tabellar til "sticky" via prop på `<Table.Header />`.
Minimumsløysing: gjere det lettare for utviklarar å gjere det sjølv ved å endre `border-collapse: collapse` på table til 
```
border-collapse: separate;
border-spacing: 0;
```

## Kva løyser dette?
Enklare for brukarar:
- Mindre mental last når dei scrollar i lange tabellar, fordi dei slepp å hugse kva kolonner dei ser på.
- Slepp scrolle opp til toppen igjen for å finne ut kva dei ser på.
- Enklare for veiledarar å gjere jobben sin, då fleire system bruker tabellar til å vise store mengdar brukarar. Døme: "Min oversikt" i Modia Arbeidsrettet oppfølging.

Enklare for utviklarar:
- Slepp å overskrive styling frå designsystemet, mindre arbeid.
- Minkar risiko for ulikheiter i styling frå Aksel og i løysingane, spesielt om designet i Aksel endrar seg over tid.
- Sparer tid: slepp setje seg inn i den litt kronglete logikken rundt `position: sticky` i element i tabellar.

### Problem 1: Å gjere header sticky
`display: table` og `position: sticky` er ikkje så gode vennar. Nærare bestemt: ein kan ikkje setje `sticky` på `thead` eller `row`. Heldigvis kan ein endre `position` på `td` og `th`.

#### Kode
Set `position: relative` på sjølve tabellen, og `position: sticky;` og `top: 0` på alle th-elementa.

```css
table:has(.sticky-table-header) {
  position: relative; /* Avgrensar området th skal vere sticky inni */
}

table thead.sticky-table-header th {
  position: sticky; /* Gjer th sticky */ 
  top: 0; /* Fortel th kva kant/posisjon den skal klistre seg til */
}

```

#### Video (før)

https://github.com/user-attachments/assets/1d985b5f-da4a-4e52-9934-d15b14d67341

#### Video (etter)
No fungerer sticky, men cellene er gjennomsiktige.

https://github.com/user-attachments/assets/af496de5-f126-4b59-8aa7-3e087ccc3ba4

### Problem 2: Bakgrunn på sticky celler
Bakgrunnsfarge i tabellar følgjer sjeldan th/td-elementa, den ligg på sjølve table. Utan bakgrunnsfarge får ein spanande overlapp mellom tekstar i tabellen, som i filmklippet over.

### Kode
Legg til bakgrunnsfarge på th-ane, ideelt sett den same som bakgrunnen på th (om den er sett), kanskje defaulte til `var(--a-bg-default)`.

```css
table:has(.sticky-table-header) {
  position: relative; /* Avgrensar området th skal vere sticky inni */
}

table thead.sticky-table-header th {
  position: sticky; /* Gjer th sticky */ 
  top: 0; /* Fortel th kva kant/posisjon den skal klistre seg til */
  background: var(--a-bg-white); /* Skjular innhald som scrollar forbi bak sticky headercelle */
}
```

#### Video (etter)
Cellene har bakgrunn, men border heng ikkje med når ein scrollar.

https://github.com/user-attachments/assets/ecf463ef-bea4-4c56-9868-4dc25ce3242c

### Problem 3: Border ved sticky header
`border-collapse: collapse` gjer at kantane ikkje "sit fast" i cellene dei er rundt. For å fikse dette må ein endre til `border-collapse: separate`, og berre style `border-bottom`. Eg trur det er lurt å gjere det for alle tabellar, ikkje berre dei som er sticky for å gjere oppførselen forutsigbar.

Det er denne stylinga eg trur har størst risiko for å skape trøbbel hos brukarar av <Table />, dersom dei har overskrive Aksel-stylinga med eiga styling.

#### Kode

```css
table {
    border-collapse: separate; /* Gjer at border kan scrolle saman med sticky header*/
    border-spacing: 0; /* Nullar ut default-verdi der det er avstand mellom cellene sine kantar */

}

table:has(.sticky-table-header) {
  position: relative; /* Avgrensar området th skal vere sticky inni */
}

table thead.sticky-table-header th {
  --sticky-top-position-distance: 0;
  position: sticky; /* Gjer th sticky */ 
  top: var(--sticky-top-position-distance); /* Fortel th kva kant/posisjon den skal klistre seg til */
  background: var(--a-bg-white); /* Skjular innhald som scrollar forbi bak sticky headercelle */
}
```

#### Video (etter)

https://github.com/user-attachments/assets/4501d2fe-8dfe-459d-85f6-41c23c04d903

## Andre tankar om løysinga
Det er fint om ein kan setje sticky som ein prop, til dømes på `<Table.Header />`. 

```
<Table.Header stickyHeader={true} />
```

Eg trur ikkje det er stort behov for å kunne overskrive `--sticky-top-position-distance`. I ei av løysingane våre har vi to sticky element på rad (men på ulike nivå i hierarkiet), og lettaste måte å få dei til å fungere er å endre offset i `top`. Dette er likevel så sært at 
a) vi burde finne ein annan fiks enn å overskrive `top`
b) om vi skal overskrive den kan vi gjere det sjølv, det trengs ikkje ekstra kompleksitet for dette.

## Kjelder / relevant lesestoff
Artikkel som forklarar problemet med sticky i tabellar: https://css-tricks.com/position-sticky-and-table-headers/
StackOverflow om border på sticky celler: https://stackoverflow.com/a/53559396
Slacktråd i #aksel-designsystemet: https://nav-it.slack.com/archives/C7NE7A8UF/p1744100993652509

Kode-eksempel frå "beslutteroversikt" i Modia: https://github.com/navikt/beslutteroversikt/pull/363
Demo på https://navikt.github.io/beslutteroversikt (eventuelt https://beslutteroversikt.intern.dev.nav.no om du har tilgang til Modia i dev)
